/**
 * SObjectFieldAPINameConstants Class with constants for fields API names
 */
public with sharing class SObjectFieldAPINameConstants {
  public static final String ACCOUNT = 'Account';
  public static final String CONTACT = 'Contact';
  public static final String PRODUCT = 'Product2';
  public static final String ASSET = 'Asset';
  public static final String INCIDENT = 'Incident';
  public static final String ID = 'Id';
  public static final String ASSET_ID = 'AssetId';
  public static final String ASSET_NAME = 'Name';
  public static final String ASSET_LATITUDE = 'Latitude';
  public static final String ASSET_LONGITUDE = 'Longitude';
  public static final String ASSET_STATUS = 'Status';
  public static final String INCIDENT_NUMBER = 'IncidentNumber';
  public static final String INCIDENT_ID = 'IncidentId';
  public static final String INCIDENT_STATUS = 'Status';
  public static final String ACCOUNT_ID = 'AccountId';
  public static final String ACCOUNT_NAME = 'Name';
  public static final String CONTACT_ID = 'ContactId';
  public static final String CONTACT_NAME = 'Name';
  public static final String PRODUCT_ID = 'Product2Id';
  public static final String PRODUCT_NAME = 'Name';
  public static final String PRODUCT_FAMILY = 'Family';
  public static final String CASE_OBJECT = 'Case';
}
