name: Apex Test runner

on:
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  apexTests:
    # The type of runner that the job will run on
    runs-on: vaccinecloud-ubuntu
    env:
      # ToDo - Change in Vaccine Cloud org
      GITHUB_TOKEN: ${{ secrets.KLUN_GITHUB_TOKEN }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: install sfdx
        run: npm install sfdx-cli --global

      - name: install cci
        run: pipx install cumulusci

      - name: Authenticate to using sfdxurl credential in here https://salesforce.quip.com/ZaFrAWLh4HU9#YNDACAkWDqZ
        run: |
          echo ${{ secrets.AUTH_FILE }} > authFile.txt
          sfdx force:auth:sfdxurl:store -f authFile.txt -a devHub --setdefaultdevhubusername

      - name: Check out repo
        uses: actions/checkout@v2

      - name: create dev org
        run: cci org info dev
      
      - name: push changes
        run: cci flow run dev_org --org dev

      - name: run apex test
        run: cci task run run_tests --org dev
      
      - name: Delete scratch org
        if: ${{ always() }}
        run: cci org scratch_delete dev
