name: LWC Jest Runner

on:
  pull_request:
    branches:
      - main
      - develop

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  jest:
    # The type of runner that the job will run on
    runs-on: vaccinecloud-ubuntu

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        
      - name: install sfdx
        run: npm install sfdx-cli --global

      - name: install cci
        run: pipx install https://github.com/SFDO-Tooling/CumulusCI/archive/refs/tags/v3.64.0.tar.gz

      # Installing pre-release to avoid api version issue during pre release development
      - name: install lwc-jest
        run: npm install @salesforce/sfdx-lwc-jest@prerelease --save-dev

      - name: install sa11y
        run: npm install -D @sa11y/jest

      - name: 'Install npm dependencies'
        run: npm ci

      - name: run lwc jest for code coverage
        run: npm run test:unit:coverage:verbose
