name: Run pmd rules in pull request

on:
  pull_request:
    branches:
      - main
      - develop

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  pmd:
    # The type of runner that the job will run on
    runs-on: vaccinecloud-ubuntu

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Check out repo
        uses: actions/checkout@v2

      - name: run-pmd
        run: ./pmdRunner.sh
